version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9300:9300
      - 9200:9200
    command: bin/elasticsearch -E network.host=0.0.0.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
  postgres:
    image: postgres:9-alpine
    ports:
      - 5432:5432
